# Generated by Django 3.2.4 on 2021-06-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cant_prod', models.IntegerField(max_length=2000)),
                ('prod_val', models.IntegerField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=64)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.IntegerField(max_length=10)),
            ],
        ),
    ]
