# Generated by Django 3.2.4 on 2021-06-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='cant_prod',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='archivos',
            name='prod_val',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
